import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
// @ts-ignore: side-effect import of global CSS without type declarations
import "./globals.css";
import BackToTop from "@/components/custom/ui/BackToTop";
import Navbar from "@/components/custom/layout/Navbar";


const geistMono = Geist_Mono({
  subsets: ["latin"],
});
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${geistMono.className} antialiased`}
      >
        <Navbar />
        {children}
         <BackToTop />
      </body>
    </html>
  );
}
